### ISSUE TITLE
CETopic and BERTopic training fails.

### ISSUE THREAD

**Issue by devanshrj** [hyintell/topicx#3]
- Python version: 3.7.13
- Operating System: Ubuntu 16.04.7 LTS

## Description
Hi, I am trying to train CETopic and BERTopic on a custom dataset consisting around 400K English tweets. The models train successfully on a very small subset of the same dataset, but training fails on the full dataset.

## What I Did
```python
dataset = Dataset()
dataset.load_custom_dataset_from_folder(dataset_path)
tm = CETopicTM(dataset=dataset, topic_model='cetopic', num_topics=200,
               embedding='sentence-transformers/bert-base-nli-mean-tokens', 
               word_select_method='tfidf_idfi', dim_size=1, seed=42)
print("Begin model training...")
tm.train()
topic_words = tm.get_topics()
```

The following error message was displayed for both models.
```
Begin model training...
Traceback (most recent call last):
  File "cetopic_train.py", line 32, in <module>
    tm.train()
  File "/home/devanshjain/mlda/topicx/baselines/cetopictm.py", line 32, in train
    self.topics = self.model.fit_transform(self.sentences)
  File "/home/devanshjain/mlda/topicx/baselines/cetopic/cetopic.py", line 55, in fit_transform
    embeddings = self._extract_embeddings(documents.Document)
  File "/home/devanshjain/mlda/topicx/baselines/cetopic/cetopic.py", line 84, in _extract_embeddings
    embeddings = self.embedding_model.embed_documents(documents)
  File "/home/devanshjain/mlda/topicx/baselines/cetopic/backend/_base.py", line 69, in embed_documents
    return self.embed(document, verbose)
  File "/home/devanshjain/mlda/topicx/baselines/cetopic/backend/_flair.py", line 71, in embed
    self.embedding_model.embed(sentence)
  File "/home/devanshjain/miniconda3/envs/cetopic/lib/python3.7/site-packages/flair/embeddings/base.py", line 62, in embed
    self._add_embeddings_internal(data_points)
  File "/home/devanshjain/miniconda3/envs/cetopic/lib/python3.7/site-packages/flair/embeddings/base.py", line 766, in _add_embeddings_internal
    self._add_embeddings_to_sentences(expanded_sentences)
  File "/home/devanshjain/miniconda3/envs/cetopic/lib/python3.7/site-packages/flair/embeddings/base.py", line 684, in _add_embeddings_to_sentences
    return_tensors="pt",
  File "/home/devanshjain/miniconda3/envs/cetopic/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 2512, in __call__
    **kwargs,
  File "/home/devanshjain/miniconda3/envs/cetopic/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 2703, in batch_encode_plus
    **kwargs,
  File "/home/devanshjain/miniconda3/envs/cetopic/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py", line 459, in _batch_encode_plus
    for key in tokens_and_encodings[0][0].keys():
IndexError: list index out of range
```

Thanks for the nice work by the way!

**Comment by ZhangzihanGit** [comment]
Hi,

There could be a lot of reasons for this issue. One possible reason might be in your dataset. 

In the paper, we use OCTIS to load the preprocessed dataset. When you experiment on your custom dataset, have you followed their preprocessing [format](https://github.com/MIND-Lab/OCTIS#load-a-custom-dataset)?

After preprocessing your data, is it possible that some of the sentences become empty strings, which might cause this issue, like this [one](https://github.com/huggingface/tokenizers/issues/993)? Since the small subset of the same dataset works fine.

Lastly, 400k data is very huge, which may take a long time for training, and we didn't test our methods on such big data. As suggested by BERTopic, you could also try methods [here](https://github.com/MaartenGr/BERTopic/issues/491) and [here](https://github.com/MaartenGr/BERTopic/issues/151).

Thanks,

**Comment by devanshrj** [comment]
Thanks for the prompt response. It was an issue with empty strings after tokenisation. 
I added a `try...except` block to skip the empty strings and the model worked fine! Thanks for the help.
